### ISSUE TITLE
touchesMoved

### ISSUE THREAD

**Issue by byelik** [ryanmeisters/UIView-DragDrop#8]
Hi. I have a question. How I can see updated position of dragView1?
method touchesMoved is not calling. Testing on your sample.

**Comment by ryanmeisters** [comment]
Hi byelik. I'm not sure what you mean. 

As a quick test, in the sample application:
1. Create a subclass of UIView called TestView
2. Implement touchesMoved
3. Change the class of dragView1 to TestView in Main.storyboard
The drag view is draggable and touchesMoved is called. 

Is that what you're going for?

**Comment by byelik** [comment]
> 6 лист. 2015 р. о 19:22 Ryan Meisters <notifications@github.com> написав(ла):
> 
> Hi byelik. I'm not sure what you mean.
> 
> As a quick test, in the sample application:
> 1. Create a subclass of UIView called TestView
> 2. Implement touchesMoved
> 3. Change the class of dragView1 to TestView in Main.storyboard
> The drag view is draggable and touchesMoved is called.
> 
every time?

**Comment by ryanmeisters** [comment]
every time?
